### ISSUE TITLE
Crashing upon right clicking any type of torcherino/lanterino

### ISSUE THREAD

**Issue by SnowbodyX** [NinjaPhenix/Torcherino#17]
Minecraft (1.14.4) crashes the moment I right click on any of the torcherino/lanterino's, with no other mods installed. Crash log is uploaded to the pastebin link. 
[https://pastebin.com/S9sUStJq](https://pastebin.com/S9sUStJq)

**Comment by NinjaPhenix** [comment]
Fixed in most recent build ( was just a silly mistake on my part ). Also backported some of the more recent changes to 1.14.4, build can be found here: [Torcherino 2.11.62+1.14.4](https://www.curseforge.com/minecraft/mc-mods/torcherino/files/2895955) ( may still be being approved takes up to 5 minutes usually. )
